services:
  nuxt:
    build: ./frontend
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_URL=http://express-api:5000
    env_file:
      - ./frontend/.env
    networks:
      - burlive

  bot:
    build: ../burlive-bot
    container_name: telegram-bot
    restart: always
    environment:
      - API_URL=http://express-api:5000
    ports: 
      - "1442:1442"
    env_file:
      - ../burlive-bot/.env
    depends_on:
      - api
    volumes:
      - /opt/burlive-bot/src/logs:/app/src/logs
    networks:
      - burlive

  api:
    build: ./api
    container_name: express-api
    restart: always
    environment:
      - MONGO_URL=${MONGO_URL}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./uploads:/var/www/burlive/uploads
      - ./api/src/logs:/app/src/logs
    networks:
      - burlive

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - burlive

networks:
  burlive:
    external: true

volumes:
  mongo_data: